### ISSUE TITLE
BUG: error thrown from ClassDeclaration when using argument default

### ISSUE THREAD

**Issue by nazimjamil** [lessmess-dev/gen-flow-files#5]
Issue: When generating .flow.js files the build fails with the following error: TypeError: Property name expected type of string but got null

Steps to reproduce:

Try to run gen-flow-files on a Class structured like this:
```
type TitleType = {
  title: 'Mr' | 'Ms' | 'Dr',
};

class TestClass {
    static TestClassFunc(title: TitleType = 'Mr') {
    ...
```
Expected Result:
* A testClass.flow.js file

Actual Result:
* An error
* No files generated

Additional:

It only happens when a method in the class is using a default in the arguments.
Environment:
macOS 10.14.2
node v8.11.3
yarn v1.5.1
flow-bin v^0.94.0
gen-flow-files v^0.4.4

**Comment by ilyalesik** [comment]
Hi, @nazimjamil. Thank you for report. I fix this issue at 0.4.5.
